apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'SDLC-lusters'
spec:
  destination:
    name: 'in-cluster'
    namespace: 'argocd'
  source:
    path: 'clusters/'
    repoURL: 'git@github.com:faisalshahdad18/kubecon-slc-ack-argocd.git'
    targetRevision: HEAD
  project: 'default'
