apiVersion: ec2.services.k8s.aws/v1alpha1
kind: ElasticIPAddress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}-eip
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: {}

