apiVersion: ec2.services.k8s.aws/v1alpha1
kind: InternetGateway
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}-igw
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  vpcRef:
    from:
      name: {{ .Values.namespace }}-vpc

