apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    services.k8s.aws/owner-account-id: "{{ .Values.accountID }}"
    services.k8s.aws/default-region: "{{ .Values.region }}"