apiVersion: ec2.services.k8s.aws/v1alpha1
kind: NATGateway
metadata:
  namespace: {{ .Values.namespace }}
  name: epam-d-cluster-natgateway1
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  subnetRef:
    from:
      name: epam-d-cluster-public-subnet2
  allocationRef:
    from:
      name: epam-d-cluster-eip

