apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}-nodegroup
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  name: d-ng
  diskSize: {{ .Values.nodegroup.diskSize }}
  clusterRef:
    from:
      name: {{ .Values.namespace }}
  subnetRefs:
  - from:
      name: {{ .Values.namespace }}-public-subnet1
  - from:
      name: {{ .Values.namespace }}-public-subnet2
  nodeRoleRef:
    from:
      name: {{ .Values.namespace }}-node-role
  updateConfig:
    maxUnavailable: 1
  scalingConfig:
    minSize: {{ .Values.nodegroup.scalingConfig.minSize }}
    maxSize: {{ .Values.nodegroup.scalingConfig.maxSize }}
    desiredSize: {{ .Values.nodegroup.scalingConfig.desiredSize }}

