apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}-pia-role
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  name: {{ .Values.namespace }}-pia-role
  description: "Pod Identity Assumer role for the dev cluster"
  policies:
    - arn:aws:iam::aws:policy/AdministratorAccess
  assumeRolePolicyDocument: |
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "AllowEksAuthToAssumeRoleForPodIdentity",
                "Effect": "Allow",
                "Principal": {
                    "Service": "pods.eks.amazonaws.com"
                },
                "Action": [
                    "sts:AssumeRole",
                    "sts:TagSession"
                ]
            }
        ]
    }

