apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Subnet
metadata:
  namespace: {{ .Values.namespace }}
  name: epam-d-cluster-public-subnet1
spec:
  availabilityZone: {{ .Values.subnet1.availabilityZone }}
  cidrBlock: {{ .Values.subnet1.cidrBlock }}
  vpcRef:
    from:
      name: epam-d-cluster-vpc
  routeTableRefs:
  - from:
      name: epam-d-cluster-public-route-table
  mapPublicIPOnLaunch: true

