apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Subnet
metadata:
  namespace: {{ .Values.namespace }}
  name: epam-d-cluster-public-subnet2
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  availabilityZone: {{ .Values.subnet2.availabilityZone }}
  cidrBlock: {{ .Values.subnet2.cidrBlock }}
  vpcRef:
    from:
      name: epam-d-cluster-vpc
  routeTableRefs:
  - from:
      name: epam-d-cluster-public-route-table
  mapPublicIPOnLaunch: true

