apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPC
metadata:
  namespace: {{ .Values.namespace }}
  name: epam-d-cluster-vpc
spec:
  cidrBlocks:
  - {{ .Values.vpc.cidrBlocks | join "," }}
  enableDNSSupport: {{ .Values.vpc.enableDNSSupport }}
  enableDNSHostnames: {{ .Values.vpc.enableDNSHostnames }}

