apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'ekscluster-dev'
spec:
  destination:
    name: 'in-cluster'
  source:
    path: 'charts/sdlc-clusters'
    repoURL: 'git@github.com:faisalshahdad18/kubecon-slc-ack-argocd.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-dev.yaml
  project: 'default'
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground