apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'scoreboard-dev'
spec:
  destination:
    name: 'in-cluster'
    namespace: 'dev'
  source:
    path: 'charts/scoreboard'
    repoURL: 'git@github.com:faisalshahdad18/kubecon-slc-ack-argocd.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-dev.yaml
  project: 'default'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
